services:
  - type: web
    name: resume-scoring-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn resume_scoring.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
