# Generated by Django 5.2.3 on 2025-07-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoredResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='resumes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('top1_role', models.CharField(blank=True, max_length=255, null=True)),
                ('top1_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('top1_category', models.CharField(blank=True, max_length=50, null=True)),
                ('top2_role', models.CharField(blank=True, max_length=255, null=True)),
                ('top2_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('top2_category', models.CharField(blank=True, max_length=50, null=True)),
                ('top3_role', models.CharField(blank=True, max_length=255, null=True)),
                ('top3_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('top3_category', models.CharField(blank=True, max_length=50, null=True)),
                ('top4_role', models.CharField(blank=True, max_length=255, null=True)),
                ('top4_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('top4_category', models.CharField(blank=True, max_length=50, null=True)),
                ('top5_role', models.CharField(blank=True, max_length=255, null=True)),
                ('top5_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('top5_category', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
